{
 "title": "PCD Synthetics Single Monitor",
 "tags": [
  "synthetic",
  "pcd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "nova : %nova%, neutron : %neutron%, glance : %glance%, cinder : %cinder%, placement : %placement%, resmgr : %resmgr%"
   },
   { "name": "name_filter", "query": "%pcd-scale-india%" },
   { "name": "limit", "query": "50000" }
  ]
 },
 "panels": [
  {
   "title": "Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Monitor durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as nova, time \nFROM synthehol.monitor_results  \nWHERE $__timeFilter(time) AND name LIKE '$service' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT count(id) \nFROM synthehol.monitor_results\nWHERE status > 0\nAND name LIKE '$name_filter' \nAND name LIKE '$service' \nAND $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Monitor Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT MAX(status) as status, time \nFROM synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '$service' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    }
   ]
  },
  {
   "title": "Duration Average",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT AVG(duration/1000) as duration_ms, time \nFROM synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '$service' AND name LIKE '$name_filter'\nGROUP BY time, duration\nLIMIT $limit\n"
    }
   ]
  },
  {
   "title": "Duration Percentiles",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT percentile_cont(.50) within group (order by duration_ms asc) as \"50th\" from (select duration/1000 as duration_ms from synthehol.monitor_results where name LIKE '$name_filter' and name LIKE '$service');"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT percentile_cont(.90) within group (order by duration_ms asc) as \"90th\" from (select duration/1000 as duration_ms from synthehol.monitor_results where name LIKE '$name_filter' and name LIKE '$service');\r\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT percentile_cont(.95) within group (order by duration_ms asc) as \"95th\" from (select duration/1000 as duration_ms from synthehol.monitor_results where name LIKE '$name_filter' and name LIKE '$service');"
    }
   ]
  },
  {
   "title": "Duration Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT duration/1000 as duration, time \nFROM synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '$service' AND name LIKE '$name_filter'\nGROUP BY time, duration\nLIMIT $limit\n"
    }
   ]
  },
  {
   "title": "Monitor logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT time, duration/1000 as duration_ms, status, name, stdout \nFROM synthehol.monitor_results \nWHERE name LIKE '$name_filter' AND name LIKE '$service' AND $__timeFilter(time) \nORDER BY time\nLIMIT 250\n"
    }
   ]
  }
 ]
}