{
 "title": "PCD Synthetics Overview",
 "tags": [
  "pcd",
  "synthetic"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "name_filter", "label": "name", "query": "%pcd-scale-india%" },
   { "name": "limit", "query": "5000" }
  ]
 },
 "panels": [
  {
   "title": "Nova Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Neutron Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Cinder Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Glance Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Placement Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Resmgr Success %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$success/$total", "type": "math" }
   ]
  },
  {
   "title": "Monitor Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"nova\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%nova%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"neutron\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%neutron%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"cinder\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%cinder%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"glance\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%glance%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"placement\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%placement%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT\n    time,\n    AVG(GREATEST(0, LEAST(1, status))) OVER (\n        ORDER BY time\n        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW\n    ) AS \"resmgr\"\nFROM\n    synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%resmgr%' AND name LIKE '$name_filter'\nLIMIT $limit\n"
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT count(id) as failures, name as monitor\nFROM synthehol.monitor_results\nWHERE status > 0\nAND name LIKE '$name_filter' \nAND $__timeFilter(time) \nGROUP BY name"
    }
   ]
  },
  {
   "title": "Monitor durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as nova, time \nFROM synthehol.monitor_results  \nWHERE $__timeFilter(time) AND name LIKE '%nova%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as neutron, time \nFROM synthehol.monitor_results  \nWHERE $__timeFilter(time) AND name LIKE '%neutron%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as glance, time \nFROM synthehol.monitor_results  \nWHERE $__timeFilter(time) AND name LIKE '%glance%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as cinder, time \nFROM synthehol.monitor_results \nWHERE $__timeFilter(time) AND name LIKE '%cinder%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as placement, time \nFROM synthehol.monitor_results\nWHERE $__timeFilter(time) AND name LIKE '%placement%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    },
    {
     "dataset": "ps_db",
     "rawSql": "SELECT avg(duration/1000) as resmgr, time \nFROM synthehol.monitor_results\nWHERE $__timeFilter(time) AND name LIKE '%resmgr%' AND name LIKE '$name_filter'\nGROUP BY time\nLIMIT $limit\n"
    }
   ]
  }
 ]
}